-- Inbound AI Intake module.
-- Self-contained: creates only inbound_* tables and does not alter any outbound table.

-- ---------- Settings (singleton) ----------
CREATE TABLE IF NOT EXISTS public.inbound_settings (
  id smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  flags jsonb NOT NULL DEFAULT '{}'::jsonb,
  business_hours jsonb NOT NULL DEFAULT '{}'::jsonb,
  routing jsonb NOT NULL DEFAULT '{}'::jsonb,
  contracts jsonb NOT NULL DEFAULT '{}'::jsonb,
  qualification jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_by uuid REFERENCES auth.users(id),
  updated_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO public.inbound_settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- ---------- Agent instructions (versioned) ----------
CREATE TABLE IF NOT EXISTS public.inbound_agent_instructions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  version integer NOT NULL UNIQUE,
  content jsonb NOT NULL,
  is_active boolean NOT NULL DEFAULT false,
  note text,
  created_by uuid REFERENCES auth.users(id),
  created_by_email text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS inbound_agent_instructions_one_active
  ON public.inbound_agent_instructions (is_active) WHERE is_active;

-- ---------- Calls ----------
CREATE TABLE IF NOT EXISTS public.inbound_calls (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  twilio_call_sid text UNIQUE,
  xai_call_id text,
  from_number text,
  to_number text,
  forwarded_from text,
  status text NOT NULL DEFAULT 'ringing',
  language text NOT NULL DEFAULT 'en',
  business_status text,
  transfer_status text,
  transferred_to text,
  end_reason text,
  simulated boolean NOT NULL DEFAULT false,
  started_at timestamptz NOT NULL DEFAULT now(),
  answered_at timestamptz,
  ended_at timestamptz,
  duration_seconds integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS inbound_calls_started_at_idx ON public.inbound_calls (started_at DESC);
CREATE INDEX IF NOT EXISTS inbound_calls_status_idx ON public.inbound_calls (status);

-- ---------- Intakes ----------
CREATE TABLE IF NOT EXISTS public.inbound_intakes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  call_id uuid REFERENCES public.inbound_calls(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'active',
  caller_type text,
  caller_name text,
  phone text,
  email text,
  language text NOT NULL DEFAULT 'en',
  case_type text,
  incident_date date,
  incident_state text,
  qualification_result text,
  qualification_reasons jsonb NOT NULL DEFAULT '[]'::jsonb,
  high_priority boolean NOT NULL DEFAULT false,
  high_priority_reasons jsonb NOT NULL DEFAULT '[]'::jsonb,
  needs_review_reasons jsonb NOT NULL DEFAULT '[]'::jsonb,
  recommended_next_action text,
  can_send_contract boolean NOT NULL DEFAULT false,
  contract_status text NOT NULL DEFAULT 'none',
  contract_provider text,
  contract_external_id text,
  contract_sent_at timestamptz,
  contract_signed_at timestamptz,
  callback_requested boolean NOT NULL DEFAULT false,
  facts jsonb NOT NULL DEFAULT '{}'::jsonb,
  -- Full engine state (transfers, callbacks, contract, qualification) so a call can resume after a failed transfer.
  state jsonb NOT NULL DEFAULT '{}'::jsonb,
  summary text,
  staff_notes text,
  reviewed_by uuid REFERENCES auth.users(id),
  reviewed_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS inbound_intakes_call_id_idx ON public.inbound_intakes (call_id);
CREATE INDEX IF NOT EXISTS inbound_intakes_created_at_idx ON public.inbound_intakes (created_at DESC);
CREATE INDEX IF NOT EXISTS inbound_intakes_status_idx ON public.inbound_intakes (status);
CREATE INDEX IF NOT EXISTS inbound_intakes_qualification_idx ON public.inbound_intakes (qualification_result);
CREATE INDEX IF NOT EXISTS inbound_intakes_contract_external_idx ON public.inbound_intakes (contract_external_id);

-- ---------- Transcript ----------
CREATE TABLE IF NOT EXISTS public.inbound_transcript_segments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  call_id uuid NOT NULL REFERENCES public.inbound_calls(id) ON DELETE CASCADE,
  speaker text NOT NULL CHECK (speaker IN ('caller', 'agent', 'system')),
  text text NOT NULL,
  language text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS inbound_transcript_call_idx ON public.inbound_transcript_segments (call_id, id);

-- ---------- Audit (append-only) ----------
CREATE TABLE IF NOT EXISTS public.inbound_audit_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  call_id uuid REFERENCES public.inbound_calls(id) ON DELETE SET NULL,
  intake_id uuid REFERENCES public.inbound_intakes(id) ON DELETE SET NULL,
  event_type text NOT NULL,
  actor text NOT NULL CHECK (actor IN ('AI', 'SYSTEM', 'ADMIN', 'HUMAN')),
  actor_user_id uuid REFERENCES auth.users(id),
  event_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS inbound_audit_call_idx ON public.inbound_audit_events (call_id, id);
CREATE INDEX IF NOT EXISTS inbound_audit_intake_idx ON public.inbound_audit_events (intake_id, id);
CREATE INDEX IF NOT EXISTS inbound_audit_created_idx ON public.inbound_audit_events (created_at DESC);

-- ---------- Callback requests ----------
CREATE TABLE IF NOT EXISTS public.inbound_callback_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  intake_id uuid REFERENCES public.inbound_intakes(id) ON DELETE CASCADE,
  call_id uuid REFERENCES public.inbound_calls(id) ON DELETE SET NULL,
  priority text NOT NULL DEFAULT 'normal' CHECK (priority IN ('urgent', 'normal')),
  reason text NOT NULL,
  preferred_time text,
  phone text,
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'done')),
  completed_by uuid REFERENCES auth.users(id),
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS inbound_callbacks_open_idx ON public.inbound_callback_requests (status, priority, created_at DESC);

-- ---------- updated_at triggers ----------
DROP TRIGGER IF EXISTS inbound_calls_updated_at ON public.inbound_calls;
CREATE TRIGGER inbound_calls_updated_at BEFORE UPDATE ON public.inbound_calls
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS inbound_intakes_updated_at ON public.inbound_intakes;
CREATE TRIGGER inbound_intakes_updated_at BEFORE UPDATE ON public.inbound_intakes
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ---------- RLS ----------
-- The voice worker uses the service role (bypasses RLS). Staff with an active role can read
-- everything and edit settings / instructions / intake review fields. Audit is insert-only.
ALTER TABLE public.inbound_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inbound_agent_instructions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inbound_calls ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inbound_intakes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inbound_transcript_segments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inbound_audit_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inbound_callback_requests ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'inbound_settings', 'inbound_agent_instructions', 'inbound_calls', 'inbound_intakes',
    'inbound_transcript_segments', 'inbound_audit_events', 'inbound_callback_requests'
  ] LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', t || '_select', t);
    EXECUTE format(
      'CREATE POLICY %I ON public.%I FOR SELECT TO authenticated USING (public.user_has_active_role(auth.uid()))',
      t || '_select', t);
  END LOOP;

  FOREACH t IN ARRAY ARRAY['inbound_settings', 'inbound_intakes', 'inbound_callback_requests'] LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', t || '_update', t);
    EXECUTE format(
      'CREATE POLICY %I ON public.%I FOR UPDATE TO authenticated USING (public.user_has_active_role(auth.uid())) WITH CHECK (public.user_has_active_role(auth.uid()))',
      t || '_update', t);
  END LOOP;

  FOREACH t IN ARRAY ARRAY['inbound_agent_instructions', 'inbound_audit_events'] LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', t || '_insert', t);
    EXECUTE format(
      'CREATE POLICY %I ON public.%I FOR INSERT TO authenticated WITH CHECK (public.user_has_active_role(auth.uid()))',
      t || '_insert', t);
  END LOOP;
END $$;

-- Instruction activation flips is_active on older versions.
DROP POLICY IF EXISTS inbound_agent_instructions_update ON public.inbound_agent_instructions;
CREATE POLICY inbound_agent_instructions_update ON public.inbound_agent_instructions
  FOR UPDATE TO authenticated
  USING (public.user_has_active_role(auth.uid()))
  WITH CHECK (public.user_has_active_role(auth.uid()));
